### PR TITLE
Load extension specific itemset

### LINKED ISSUE #73: Validation of form with external CSV fails
#### Software versions 
Validate v1.13

#### Problem description
Form with CSV external data fails validation with the following error.

```
org.javarosa.xform.parse.XFormParseException: <label> node for itemset doesn't exist! [instance(cities)/root/item/label]
	at org.javarosa.xform.parse.FormInstanceParser.verifyItemsetBindings(FormInstanceParser.java:344)
	at org.javarosa.xform.parse.FormInstanceParser.verifyBindings(FormInstanceParser.java:177)
	at org.javarosa.xform.parse.FormInstanceParser.parseInstance(FormInstanceParser.java:84)
```

#### Steps to reproduce the problem
Validate this and it fails. [ecsv.xml.zip](https://github.com/opendatakit/validate/files/3434188/ecsv.xml.zip) (source: [ecsv.xlsx](https://github.com/opendatakit/validate/files/3434184/ecsv.xlsx))

Validate this and it works. [exml.xml.zip](https://github.com/opendatakit/validate/files/3434194/exml.xml.zip) (source: [exml.xlsx](https://github.com/opendatakit/validate/files/3434185/exml.xlsx))

### PR DESCRIPTION
**Pull request by yanokwa**
Closes #73

* Added fake CSV itemset
* Changed itemset contents to make debugging easier
* Pass URI into StubReference and use last three characters to load appropriate itemset
* Parameterize existing test
* s/xslforms/xlsforms

Some concerns for a reviewer
* Make sure variable naming and case is correct
* I added a default constructor, but I'm not sure it's needed.

#### What has been done to verify that this works as intended?
Passes tests

#### Why is this the best possible solution? Were any other approaches considered?
JavaRosa loads a [different parser for the secondary instance](https://github.com/opendatakit/javarosa/blob/59611cc0755dfbaf6631866ff15d6a9a516df704/src/main/java/org/javarosa/core/model/instance/ExternalDataInstance.java#L58) based on if the src path contains `file-csv`.  Unless we change this behavior in JR, loading extension specific itemsets is our only reasonable option.

#### Are there any risks to merging this code? If so, what are they?
Nothing really. Maybe we should change the behavior in JR? But that seems more risky to me.

### CODE REVIEW

File: src/test/java/org/opendatakit/validate/ValidateExternalSecondaryInstancesTest.java [hunk 1]
```diff
@@ -13,8 +13,17 @@
...
     @Test
-    public void supports_xlsforms_value_and_label_refs_in_itemsets_using_secondary_external_instances() throws URISyntaxException {
-        final Path path = getPathOf("external_secondary_instance_non_standard_use.xml");
+    public void supports_xlsforms_value_and_label_refs_in_itemsets_using_secondary_external_instances_xml() throws URISyntaxException {
+        supports_xlsforms_value_and_label_refs_in_itemsets_using_secondary_external_instances("external_secondary_instance_non_standard_use_xml.xml");
+    }
+
+    @Test
+    public void supports_xlsforms_value_and_label_refs_in_itemsets_using_secondary_external_instances_csv() throws URISyntaxException {
+        supports_xlsforms_value_and_label_refs_in_itemsets_using_secondary_external_instances("external_secondary_instance_non_standard_use_csv.xml");
```
Comment (lognaturel) [inline src/test/java/org/opendatakit/validate/ValidateExternalSecondaryInstancesTest.java]: For some reason this didn't catch my eye when the pattern was introduced in #69 -- what does "non-standard use" refer to?

File: src/org/opendatakit/validate/StubReference.java [hunk 2]
```diff
@@ -62,8 +80,17 @@ public String getURI() {
...
     @Override
     public String getLocalURI() {
+
+        String extension = null;
+        if (mURI != null) {
+            extension = mURI.substring(mURI.length() - 4).toLowerCase();
+        }
         try {
-            return getClass().getClassLoader().getResource("fake-itemset.xml").toURI().getPath();
+            if (extension.equals(".csv") || extension.equals(".xml")) {
```
Comment (lognaturel) [inline src/org/opendatakit/validate/StubReference.java]: Technically it's the connector (`jr://file` vs. `jr://file-csv`) that differentiates between the two. I think this is ok, though.

**Review by lognaturel — COMMENTED** [review]
Couple of questions inline.

I introduced the stub approach before we re-established CSV support. I hoped that because CSVs are virtually transformed to XML behind the scenes the same fake file could be used but I realize now that this is probably not be possible with the JavaRosa implementation (there never actually is an XML document and there's no place to blur the lines between the two). I think this is probably about the best we can do.

File: src/org/opendatakit/validate/StubReference.java [hunk 3]
```diff
@@ -45,6 +52,17 @@
...
  */
 public class StubReference implements Reference {
+
+    private String mURI;
+
+    public StubReference(String URI) {
+        mURI = URI;
+    }
+
+    public StubReference() {
```
Comment (lognaturel) [inline src/org/opendatakit/validate/StubReference.java]: Can be removed.

File: src/org/opendatakit/validate/StubReference.java [hunk 4]
```diff
@@ -45,6 +52,17 @@
  *
  */
 public class StubReference implements Reference {
+
+    private String mURI;
```
Comment (lognaturel) [inline src/org/opendatakit/validate/StubReference.java]: Remove prefixed `m`. Name should be `uri`.

File: src/test/java/org/opendatakit/validate/ValidateExternalSecondaryInstancesTest.java (hunk 1 above)
Comment (yanokwa) [reply src/test/java/org/opendatakit/validate/ValidateExternalSecondaryInstancesTest.java]: The commit history suggests "non-standard" because it's only "itemset definitions like the ones generated by XLSForm which use `<value ref="name"/>` and `<label ref="label"/>`. I don't think "non-standard" clarifies, so I'll remove it.

File: src/org/opendatakit/validate/StubReference.java (hunk 2 above)
Comment (yanokwa) [reply src/org/opendatakit/validate/StubReference.java]: I'd feel better doing it correctly.

**Review by lognaturel — APPROVED** [review]
